### ISSUE TITLE
1x Usage: self:RegisterForClicks(buttons)

### ISSUE THREAD

**Issue by Thrumbar** [bob-schumaker/fishing-ace#2]
1x Usage: self:RegisterForClicks(buttons)
[string "=[C]"]: in function `RegisterForClicks'
[string "@Interface/AddOns/FishingAce/LibFishing-1.0-101085.lua"]:1987: in function `CreateSAButton'
[string "@Interface/AddOns/FishingAce/FishingAce.lua"]:258: in function <Interface/AddOns/FishingAce/FishingAce.lua:229>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by bob-schumaker** [comment]
This will be fixed in the next version, coming out momentarily.
